create table roles (
    id bigint generated by default as identity primary key,
    name varchar(50) not null unique
);

create table users (
    id bigint generated by default as identity primary key,
    first_name varchar(50) not null,
    last_name varchar(50) not null,
    email varchar(100) not null unique,
    password_hash varchar(255) not null,
    phone_number varchar(255),
    status varchar(20) not null,
    email_verified boolean not null,
    access_token_invalid_before timestamp,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table user_roles (
    user_id bigint not null references users(id) on delete cascade,
    role_id bigint not null references roles(id) on delete restrict,
    primary key (user_id, role_id)
);

create table refresh_tokens (
    token varchar(500) primary key,
    user_id bigint not null references users(id) on delete cascade,
    expiry_date timestamp not null,
    created_at timestamp not null,
    revoked boolean not null
);

create table email_verification_tokens (
    token varchar(500) primary key,
    user_id bigint not null references users(id) on delete cascade,
    expiry_date timestamp not null,
    created_at timestamp not null,
    used boolean not null
);

create table password_reset_tokens (
    token varchar(500) primary key,
    user_id bigint not null references users(id) on delete cascade,
    expiry_date timestamp not null,
    created_at timestamp not null,
    used boolean not null
);

create table user_addresses (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id) on delete cascade,
    label varchar(50) not null,
    recipient_name varchar(100) not null,
    street varchar(255) not null,
    address_line2 varchar(255),
    city varchar(255) not null,
    state varchar(255) not null,
    zip_code varchar(255) not null,
    country varchar(2) not null,
    address_type varchar(255) not null,
    is_default boolean not null
);

create table brand (
    id bigint generated by default as identity primary key,
    name varchar(255) not null unique
);

create table category (
    id bigint generated by default as identity primary key,
    name varchar(255) not null unique
);

create table product (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    brand_id bigint references brand(id),
    price numeric(19, 2) not null,
    stock integer not null,
    description varchar(1000),
    image_url varchar(255),
    category_id bigint references category(id),
    discount_percentage integer,
    featured boolean not null default false,
    active boolean not null default true
);

create table carts (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    total_amount numeric(19, 2) not null,
    constraint carts_user_id_unique unique (user_id)
);

create table cart_items (
    id bigint generated by default as identity primary key,
    cart_id bigint not null references carts(id) on delete cascade,
    product_id bigint not null,
    product_name varchar(255) not null,
    product_description varchar(1000),
    product_image_url varchar(2048),
    quantity integer not null,
    unit_price numeric(19, 2) not null,
    total_price numeric(19, 2) not null,
    constraint cart_items_cart_product_unique unique (cart_id, product_id)
);

create table orders (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    total_amount numeric(19, 2) not null,
    status varchar(255) not null,
    order_date timestamp not null,
    shipping_full_name varchar(255) not null,
    shipping_street varchar(255) not null,
    shipping_line2 varchar(255),
    shipping_city varchar(255) not null,
    shipping_state varchar(255) not null,
    shipping_postal_code varchar(255) not null,
    shipping_country varchar(2) not null,
    shipping_delivery_notes varchar(500),
    payment_method varchar(255) not null,
    payment_provider varchar(30),
    payment_provider_order_id varchar(120),
    payment_provider_capture_id varchar(120),
    payment_status varchar(30),
    payment_failure_reason varchar(500),
    payment_created_at timestamp,
    payment_updated_at timestamp
);

create table order_items (
    id bigint generated by default as identity primary key,
    order_id bigint not null references orders(id) on delete cascade,
    product_id bigint not null,
    product_name varchar(255) not null,
    product_description varchar(1000),
    product_image_url varchar(2048),
    quantity integer not null,
    unit_price numeric(19, 2) not null,
    total_price numeric(19, 2) not null
);

create index idx_refresh_tokens_user_id on refresh_tokens(user_id);
create index idx_orders_user_id on orders(user_id);
create index idx_product_category_id on product(category_id);
create index idx_product_brand_id on product(brand_id);
